import pandas as pd
import numpy as np
from scipy.signal import savgol_filter

# Load your recorded trace from the tracing task
df = pd.read_csv("data/tracing_task.csv")  # <-- file generated by trace_task.py
time = df["time"].values
x_noisy = df["x"].values
y_noisy = df["y"].values

# Option 1: Define intent as the displayed target path
# This assumes your trace_task.py had a sine line as target
x_intent = np.linspace(0, 1, len(time))
y_intent = 0.5 * np.sin(2 * np.pi * x_intent)

# Option 2 (optional refinement): Smooth the recorded path
# x_intent = savgol_filter(x_noisy, window_length=11, polyorder=2)
# y_intent = savgol_filter(y_noisy, window_length=11, polyorder=2)

# Stack into arrays
noisy = np.stack([x_noisy, y_noisy], axis=1)
clean = np.stack([x_intent, y_intent], axis=1)

# Save for ML
np.save("data/noisy_mouse_data.npy", noisy)
np.save("data/clean_mouse_data.npy", clean)

print("Saved noisy_mouse_data.npy and clean_mouse_data.npy")
